'use client';
import PhotoUploader from './uploader';
import {useCallback,useEffect,useState} from 'react';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
type Photo={id:string,caption:string,status:string,bytes:number,name?:string};
export default function Photos({admin}:{admin:boolean}){
 const [photos,setPhotos]=useState<Photo[]>([]);const [loaded,setLoaded]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [filter,setFilter]=useState(admin?'pending':'all');
 const load=useCallback(async()=>{const r=await fetch('/api/photos',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setPhotos(d.photos);setLoaded(true)},[]);
 useEffect(()=>{load().catch(e=>setError(e.message))},[load]);
 async function send(body:FormData|{id:string,action:string}){setBusy(true);setError('');setMessage('');try{const upload=body instanceof FormData;const r=await fetch('/api/photos',{method:'POST',...(upload?{body}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();setMessage(upload?'Photo uploaded. It will appear on the homepage only after approval.':'Photo updated.');return true}catch(e:any){setError(e.message||'Unable to save. Please try again.');return false}finally{setBusy(false)}}
 const visible=photos.filter(p=>filter==='all'||p.status===filter);
 return <><p>Share a moment from club life. Approved photos appear in the homepage carousel.</p>{error&&<div className="error" role="alert">{error} {!loaded&&<button className="textlink" onClick={()=>load().catch(e=>setError(e.message))}>Try again</button>}</div>}{message&&<div className="success" role="status">{message}</div>}<PhotoUploader disabled={busy} onBusy={setBusy} onComplete={load}/>
 <div className="section-head" style={{marginTop:36}}><h2 style={{fontSize:32}}>{admin?'Review club photos':'Your photos'}</h2><div className="actions" aria-label="Filter photos">{['all','pending','approved','rejected'].map(v=><button key={v} className={'btn small '+(filter===v?'dark':'outline')} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{v==='pending'?'Awaiting approval':v[0].toUpperCase()+v.slice(1)} {v==='pending'?`(${photos.filter(p=>p.status==='pending').length})`:''}</button>)}</div></div>
 {!loaded&&!error?<p role="status">Loading photos…</p>:!visible.length?<div className="emptybox"><p>{filter==='pending'?'No photos waiting for approval.':'No photos here yet.'}</p></div>:<div className="photo-grid">{visible.map(p=><article className="photo-card" key={p.id}><a href={'/api/photos/'+p.id} target="_blank" rel="noreferrer" aria-label={p.caption?'View full photo: '+p.caption:'View full club photo'}><img src={'/api/photos/'+p.id+'?size=thumb'} alt={p.caption||'Club photo'} loading="lazy"/></a><div className="photo-card-body"><span className="pill">{p.status==='pending'?'Awaiting approval':p.status}</span>{p.caption&&<p className="photo-caption">{p.caption}</p>}<p className="subtle">{p.name?`${p.name} · `:''}{Math.round(p.bytes/1024)} KB</p><div className="actions" style={{marginTop:16}}>{admin&&p.status!=='approved'&&<button className="btn small" disabled={busy} onClick={()=>send({id:p.id,action:'approve'})}>Approve for homepage</button>}{admin&&p.status!=='rejected'&&<button className="btn outline small" disabled={busy} onClick={()=>send({id:p.id,action:'reject'})}>{p.status==='approved'?'Unpublish':'Reject'}</button>}<AlertDialog><AlertDialogTrigger asChild><button className="textlink" disabled={busy}>Delete</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this photo?</AlertDialogTitle><AlertDialogDescription>The photo will be removed from the library and homepage. This cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep photo</AlertDialogCancel><AlertDialogAction onClick={()=>send({id:p.id,action:'delete'})}>Delete photo</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></div></article>)}</div>}
 </>;
}
