'use client';
import {useState} from 'react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {EventQuestion,BookingAnswers,formatCost,readQuestions} from '@/lib/event-options';
function SelectField({label,value,onChange,choices,required=false}:{label:string,value:string,onChange:(v:string)=>void,choices:string[][],required?:boolean}){
  return <label className="field"><span>{label}</span><Select value={value} onValueChange={onChange} required={required}><SelectTrigger style={{width:'100%',minHeight:47,fontSize:16}}><SelectValue placeholder="Choose an option"/></SelectTrigger><SelectContent>{choices.map(([v,s])=><SelectItem key={v} value={v}>{s}</SelectItem>)}</SelectContent></Select></label>;
}
export function QuestionBuilder({questions,onChange}:{questions:EventQuestion[],onChange:(q:EventQuestion[])=>void}){
  function update(id:string,patch:Partial<EventQuestion>){onChange(questions.map(q=>q.id===id?{...q,...patch}:q));}
  return <section className="question-builder"><div className="section-head" style={{marginBottom:16}}><div><h3>Questions for attendees</h3><p className="subtle">Menu choices, transport or anything else you need to organise the event.</p></div><button type="button" className="btn outline small" disabled={questions.length>=10} onClick={()=>onChange([...questions,{id:crypto.randomUUID(),label:'',type:'choice',choices:[],required:false,per_guest:true}])}>+ Add question</button></div>{questions.length===0&&<p className="subtle">No extra questions. Members can respond and add guests as usual.</p>}{questions.map((q,i)=><fieldset className="question-edit" key={q.id}><legend>Question {i+1}</legend><label className="field"><span>Question</span><input required maxLength={160} value={q.label} onChange={e=>update(q.id,{label:e.target.value})} placeholder="e.g. Main course"/></label><div className="formgrid"><SelectField label="Answer type" value={q.type} onChange={v=>update(q.id,{type:v as 'text'|'choice'})} choices={[["choice","Choose one option"],["text","Written answer"]]}/><SelectField label="Ask this question" value={q.per_guest?'each':'booking'} onChange={v=>update(q.id,{per_guest:v==='each'})} choices={[["each","For the member and each guest"],["booking","Once per booking"]]}/></div>{q.type==='choice'&&<label className="field"><span>Available answers · one per line</span><textarea required value={q.choices.join('\n')} onChange={e=>update(q.id,{choices:e.target.value.split('\n')})} placeholder={'Beef\nFish\nVegetarian'}/><small>2–16 choices. Members choose one answer.</small></label>}<div className="actions" style={{justifyContent:'space-between'}}><label className="actions"><Checkbox checked={q.required} onCheckedChange={v=>update(q.id,{required:v===true})}/>Required when attending</label><button type="button" className="textlink subtle" onClick={()=>onChange(questions.filter(x=>x.id!==q.id))}>Remove question</button></div></fieldset>)}</section>;
}
function Questions({questions,answers,onChange,required}:{questions:EventQuestion[],answers:Record<string,string>,onChange:(id:string,value:string)=>void,required:boolean}){
  return <>{questions.map(q=>q.type==='choice'?<SelectField key={q.id} label={q.label+(q.required?' *':' (optional)')} value={q.choices.includes(answers[q.id])?String(q.choices.indexOf(answers[q.id])):''} onChange={v=>onChange(q.id,v==='skip'?'':q.choices[Number(v)])} required={required&&q.required} choices={[...(!q.required||!required?[['skip','No answer']]:[]),...q.choices.map((s,i)=>[String(i),s])]}/>:<label className="field" key={q.id}><span>{q.label}{q.required?' *':' (optional)'}</span><input maxLength={300} required={required&&q.required} value={answers[q.id]||''} onChange={e=>onChange(q.id,e.target.value)}/></label>)}</>;
}
export function BookingForm({event,mine,closed,busy,act}:{event:any,mine:any,closed:boolean,busy:boolean,act:(p:any)=>Promise<any>}){
  const questions=readQuestions(event.options_json);
  const[response,setResponse]=useState(mine?.response||'');
  const[guests,setGuests]=useState<number>(event.guests_allowed?mine?.guests||0:0);
  const[answers,setAnswers]=useState<BookingAnswers>({member:mine?.answers?.member||{},guests:mine?.answers?.guests||[]});
  const changed=mine&&mine.event_revision!==event.revision;
  function answer(id:string,value:string,index?:number){setAnswers(old=>index===undefined?{...old,member:{...old.member,[id]:value}}:{...old,guests:Array.from({length:guests},(_,i)=>i===index?{name:old.guests[i]?.name||'',answers:{...old.guests[i]?.answers,[id]:value}}:old.guests[i]||{name:'',answers:{}})});}
  const attending=response==='going'||response==='maybe';
  return <div className="panel"><h3>Your attendance</h3>{changed&&<div className="notice">The organiser has updated this event since your last response. Review the details and save your response again.</div>}<p className="subtle">{mine?`Saved response: ${mine.response==='going'?'Yes':mine.response==='maybe'?'Maybe':'No'}.`:'Let the organiser know if you can attend.'}</p><form onSubmit={async e=>{e.preventDefault();await act({action:'rsvp',eventId:event.id,eventRevision:event.revision,response,guests:attending?guests:0,answers})}}><fieldset disabled={busy||closed} style={{border:0,padding:0,margin:0}}><RadioGroup className="attendance-choice" aria-label="Can you attend?" value={response} onValueChange={setResponse}>{[['going','Yes, I’m coming'],['maybe','Maybe'],['declined','No, I can’t make it']].map(([v,s])=><label key={v}><RadioGroupItem value={v}/>{s}</label>)}</RadioGroup>{attending&&<>{response==='maybe'&&<p className="subtle" style={{marginBottom:18}}>You can leave required questions unanswered until you confirm Yes.</p>}{!!event.guests_allowed?<label className="field"><span>Number of guests · not including you</span><input className="guestinput" type="number" min={0} max={20} required value={guests} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=0&&n<=20)setGuests(n)}}/></label>:<p className="subtle">This event is for members only; no guests.</p>}{questions.length>0&&<div className="booking-person"><h4>Your answers</h4><Questions questions={questions} answers={answers.member} onChange={(id,v)=>answer(id,v)} required={response==='going'}/></div>}{Array.from({length:guests},(_,i)=><div className="booking-person" key={i}><h4>Guest {i+1}</h4><label className="field"><span>Guest’s name (optional)</span><input maxLength={100} value={answers.guests[i]?.name||''} onChange={e=>setAnswers(old=>({...old,guests:Array.from({length:guests},(_,j)=>j===i?{name:e.target.value,answers:old.guests[j]?.answers||{}}:old.guests[j]||{name:'',answers:{}})}))}/></label><Questions questions={questions.filter(q=>q.per_guest)} answers={answers.guests[i]?.answers||{}} onChange={(id,v)=>answer(id,v,i)} required={response==='going'}/></div>)}<div className="booking-cost"><span>{formatCost(event.cost_pence||0)} per person</span><strong>{formatCost((event.cost_pence||0)*(1+guests))} for {1+guests} {guests?'people':'person'}</strong></div>{event.cost_pence>0&&<p className="subtle">Cost shown for planning; payment is arranged with the organiser.</p>}{questions.length>0&&<p className="subtle" style={{marginTop:16}}>Your answers and guest details are visible to you and club administrators.</p>}</>}<button className="btn" style={{marginTop:22}} disabled={busy||closed||!response}>{busy?'Saving…':'Save attendance and answers'}</button></fieldset></form></div>;
}
export function OrganiserAnswers({event,responses}:{event:any,responses:any[]}){
  const questions=readQuestions(event.options_json);
  function show(raw:Record<string,string>={},guest=false){const qs=questions.filter(q=>!guest||q.per_guest);return <dl className="answer-list">{qs.map(q=><div key={q.id}><dt>{q.label}</dt><dd>{raw[q.id]||'Not answered'}</dd></div>)}{Object.entries(raw).filter(([id])=>!questions.some(q=>q.id===id)).map(([id,v])=><div key={id}><dt>Previous question (removed)</dt><dd>{v}</dd></div>)}</dl>;}
  return <div className="panel"><h3>Organiser’s booking details</h3><p className="subtle">Member and guest answers. Only club administrators can see everyone’s details here.</p>{!responses.length&&<p style={{marginTop:16}}>No responses yet.</p>}{responses.map(r=><details className="booking-summary" key={r.member_id}><summary>{r.name} · {r.response==='going'?'Yes':r.response==='maybe'?'Maybe':'No'}{r.guests?` · ${r.guests} guest${r.guests===1?'':'s'}`:''}</summary>{r.event_revision!==event.revision&&<div className="notice">Not reconfirmed since the latest event change.</div>}{r.response!=='declined'&&<><p className="subtle">Current booking cost: {formatCost((event.cost_pence||0)*(1+r.guests))}</p><h4>{r.name}</h4>{show(r.answers?.member)}{Array.from({length:r.guests},(_,i)=>{const g=r.answers?.guests?.[i];return <div key={i}><h4>{g?.name||`Guest ${i+1}`}</h4>{show(g?.answers,true)}</div>})}</>}</details>)}</div>;
}
