'use client';
import {useState} from 'react';
const pound=(n:number)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2}).format(n);
export default function TripCosts(){
 const [people,setPeople]=useState(6);
 const [flight,setFlight]=useState('330');
 const [message,setMessage]=useState('');
 const validFlight=flight.trim()!=='' && Number.isFinite(Number(flight)) && Number(flight)>=0;
 const chalet=people===6?5058:6544;
 const flightTotal=validFlight?Number(flight)*people:0;
 async function copy(){try{await navigator.clipboard.writeText('https://jerseyroundtable.com/ski-trip');setMessage('Page link copied.');}catch{setMessage('Copy this link: https://jerseyroundtable.com/ski-trip');}}
 return <div className="ski-costs"><div className="ski-controls"><fieldset><legend>Travelling together</legend><div className="ski-toggle">{[6,8].map(n=><button key={n} type="button" aria-pressed={people===n} onClick={()=>setPeople(n)}>{n} people</button>)}</div></fieldset><p>{people===6?'Three twin/double rooms · two adults per room':'Three rooms · six main beds and two bunks in room 2'} · four nights</p></div>
 <div className="ski-two ski-cost-panels"><div><span className="ski-small">HIDEAWAY 1 / LIVE CHALET QUOTE</span><strong>{pound(chalet)}</strong><p><b>{pound(chalet/people)} per person</b>. Classic chalet board, tourist tax and shared return Geneva transfers included. All three guest rooms; no extra airport-transfer charge in this calculation.</p></div><div aria-live="polite"><span className="ski-small">CHALET + ENTERED FLIGHT / SUBTOTAL</span><strong>{validFlight?pound(chalet+flightTotal):'Enter a flight amount'}</strong><p>{validFlight?<><b>{pound((chalet+flightTotal)/people)} per person</b> for {people} people. Flights contribute {pound(flightTotal)} to the group subtotal.</>:'The accommodation quote remains shown separately.'}</p></div></div>
 <div className="ski-flight-input"><label htmlFor="ski-flight-price">Return flight amount per person (£)</label><input id="ski-flight-price" type="number" min="0" step="0.01" inputMode="decimal" value={flight} onChange={e=>setFlight(e.target.value)}/><p>The default £330 is the organiser’s supplied fare for 28 January–1 February. Baggage and availability for the whole group have not been independently verified. Changing this input calculates a comparison; it does not obtain a new quote.</p></div>
 <p className="ski-note">Checked 14 September 2026. Nothing held. For six, select all three rooms with two adults each; the supplier’s default allocation may use bunks and only two rooms. For eight, two adults use bunks. The separate checked BA fare is £419.09pp for six; its eight-person price has not been checked.</p>
 <div className="ski-table-scroll"><table><caption>Hotel transfer alternatives for {people} people — advertised starting prices, not dated quotes</caption><thead><tr><th scope="col">Option</th><th scope="col">Group return model</th><th scope="col">Per person</th></tr></thead><tbody><tr><th scope="row">Avoriaz private minibus</th><td>From {pound(338)}</td><td>From {pound(338/people)}</td></tr><tr><th scope="row">Avoriaz shared shuttle</th><td>From {pound(68*people)}</td><td>From {pound(68)}</td></tr><tr><th scope="row">Les Gets private minibus</th><td>From {pound(290)}</td><td>From {pound(290/people)}</td></tr><tr><th scope="row">Les Gets shared shuttle</th><td>From {pound(38*people)}</td><td>From {pound(38)}</td></tr></tbody></table></div>
 <p className="ski-note">Transfer models double advertised one-way prices: £169/£145 per vehicle or £34/£19 per person. They do not apply to Hideaway in Argentière and are not added to its subtotal. Hotel room costs are excluded here because no complete dated group quote is confirmed.</p>
 <p className="ski-note">Still outside the Hideaway subtotal: lift passes, ski hire, food beyond chalet board, drinks beyond included dinner wine, insurance, local valley travel and any flight baggage extras. Shared-transfer pickup windows must match the selected flights.</p>
 <div className="ski-share"><button type="button" onClick={copy}>Copy page link ↗</button><button type="button" onClick={()=>window.print()}>Print / save PDF</button><span role="status">{message}</span></div>
 </div>
}
